### ISSUE TITLE
Feature Request: Implement LetsEncrypt

### ISSUE THREAD

**Issue by Remmy-OSI** [KelvinTegelaar/AzPwPush#15]
The only thing stopping me from using this immediately was the need to purchase an SSL cert

**Comment by KelvinTegelaar** [comment]
Not an option as the host is an Azure Function. you can check out https://blog.yannickreekmans.be/use-lets-encrypt-in-an-azure-function-for-an-azure-web-app/ for a way to maybe get it to work.
