### ISSUE TITLE
Security consideration - Password should not be in the URL

### ISSUE THREAD

**Issue by itfranck** [KelvinTegelaar/AzPwPush#2]
Security wise, the form should do a Post and the URL should not contain the password in clear text ever, for 2 reason.

1. Browser history
Password is saved in clear text in the browser history.
![image](https://user-images.githubusercontent.com/1980296/96297666-35c1de00-0fbf-11eb-845c-c301bb29251a.png)

2 User (Code 18) 
If the user give the url from the address bar instead of the url in the form. 
(eg: I do sometimes that by mistake with Onetimesecret.com ), you end up giving the actual password in clear text and it will never burn.

Using Onetimesecret as a reference, 
1. The form is a Post
2. The return url is an ID unrelated to the secret.
3. There's a button click to view & burn the secret from the #2 location (So that even if you give the private url away, the password is burnt as soon as it is viewed anyway.

**Comment by KelvinTegelaar** [comment]
100% agreed. @itfranck. Expect it in the next iteration. :)

**Comment by KelvinTegelaar** [comment]
Fixed
