### ISSUE TITLE
Get password screen does not display the password.

### ISSUE THREAD

**Issue by Absoblogginlutely** [KelvinTegelaar/AzPwPush#3]
I can see a couple of uses for this and wanted to check the demo version to see how it looks.

Using the demo version you posted online the get password doesn't have a password shown in the browser (Modern Edge beta) at https://pw.cyberdrain.com/Get?ID=12345678 (where 1..8) is a unique number generated previously.
![image](https://user-images.githubusercontent.com/21364480/96309001-66f7d980-0fd2-11eb-83ce-cc82b0aea8fc.png)

**Comment by KelvinTegelaar** [comment]
Currently using the demo version for some experimentation. Should be fixed soon :)

**Comment by KelvinTegelaar** [comment]
And fixed. :)
