### ISSUE TITLE
Password Creation Method may accidentally store wrong password

### ISSUE THREAD

**Issue by shellster** [KelvinTegelaar/AzPwPush#5]
Admittedly, this issue is user error, but if a user passes in a Password parameter and does not correctly escape a "=" sign, the current method of grabbing the password value, will only grab everything to the right of the last "=" sign.  This could cause serious, unintended consequences.  There is already a separate issue for the not allowing passing of a password as a GET parameter.

**Comment by KelvinTegelaar** [comment]
All passwords are send URL Encoded and only decoded right before saving. Have you seen this to be an issue and could you let me know how to reproduce? :)

**Comment by shellster** [comment]
If someone uses the Web Application, they will not run into problems.  This issue is strictly around preventing accidental user error.  Observe the following request:

`Invoke-WebRequest -Uri https://pw.cyberdrain.com/create -Method POST -Body 'password=Thiswill=break'`

Obviously, this is a user mistake (not URL encoding the parameter), but it is a fairly understandable mistake, hence in my PR why I explicitly check for "=" and store everything after the first one. If you don't believe it to be a serious enough issue, I definitely understand.

**Comment by KelvinTegelaar** [comment]
Good call, this actually makes me think of creating another endpoint for programmatic access too. I'll integrate your changes.
