### ISSUE TITLE
Feature Request: Ability to Early Delete a Password

### ISSUE THREAD

**Issue by shellster** [KelvinTegelaar/AzPwPush#9]
I'll probably implement this in my own branch sometime this next week, but I think a /Delete endpoint would be nice, and a link to that on the /Get page, so that a user can delete a password after retrieving it and not leave it lying around for 5 days or whatever if they don't want to.

**Comment by KelvinTegelaar** [comment]
/Get deletes at retrieving the password, but I am thinking of implementing 'multi-view' due to spamfilters clicking on links at times. So good idea.

**Comment by KelvinTegelaar** [comment]
/Delete endpoint has been added. With implementation of #10 we'll also add the delete button to the /Get page.
